### ISSUE TITLE
A more general IO runner

### ISSUE THREAD

**Issue by ocharles** [Gabriel439/Haskell-Typed-Spreadsheet-Library#11]
I'm playing around with some code that has its own visualiser, but it's C++ FFI code (http://pointclouds.org). I want to play with the parameters to some model, and `typed-spreadsheets` is almost perfect, but I can't interface with it and my FFI function.

I have:

```haskell
iterativeClosestPoint :: Params -> PointSet -> PointSet -> IO ()
```

This runs the iterative closest point algorithm with some parameters on two point sets. It's in `IO`, because it then opens a window and lets me visualise the result.

I'd like to use `typed-spreadsheets` to give me a window to edit `Params`, but I don't need any type of function or visualisation. I'm looking for something like:

```haskell
updates :: (a -> IO ()) -> Updatable a -> IO ()
```

It doesn't have to be this signature, but this seems the most general. I would probably use this with a `IORef` such that my rendering thread can simply be:

```haskell
readIORef params >>= \p -> iterativeClosestPoint p source target
```

I would for `updates` in a separate thread (or my renderer could be a separate thread).

What do you think? Does my request make sense?

**Comment by Gabriella439** [comment]
Yeah, that seems reasonable.  There is an internal `ui` function that might fit your need, which has this type:

```haskell
ui  :: (Gtk.HBox -> IO resource)
    -- ^ One-time setup to acquire some starting resource
    -> (resource -> event -> IO ())
    -- ^ Callback funciton
    -> Text
    -- ^ Window title
    -> Updatable event
    -- ^ Event stream
    -> IO ()
```

Would that work for you?  If so, I can export it

**Comment by ocharles** [comment]
Sure, I can work with that.

**Comment by ocharles** [comment]
Thank you!

**Comment by Gabriella439** [comment]
You're welcome! :)
