### ISSUE TITLE
How about an IHaskell backend?

### ISSUE THREAD

**Issue by rehno-lindeque** [Gabriel439/Haskell-Typed-Spreadsheet-Library#6]
It seems to me that there's some potential to put this to good use, embedded into a jupyter notebook.

**Comment by Gabriella439** [comment]
Check out the Purescript Flare library, which is the Purescript port of this library and gives you this same functionality in the browser

**Comment by rehno-lindeque** [comment]
Nice, thanks. I'm not sure if it would work in Jupyter without a purescript backend (our notebooks are in Haskell), but I'll have a look.
